.gitignore, src/main/java/oncog/cogroom/common/entity/BaseTimeEntity.java, src/main/java/oncog/cogroom/common/entity/Category.java, src/main/java/oncog/cogroom/common/response/apiErrorResponse.java, src/main/java/oncog/cogroom/common/response/apiResponse.java, src/main/java/oncog/cogroom/config/JpaAuditingConfig.java, src/main/java/oncog/cogroom/domain/auth/entity/EmailVerification.java, src/main/java/oncog/cogroom/domain/content/entity/Content.java, src/main/java/oncog/cogroom/domain/content/entity/ContentBenefit.java, src/main/java/oncog/cogroom/domain/content/entity/ContentExpectedEffect.java, src/main/java/oncog/cogroom/domain/content/entity/ContentFAQ.java, src/main/java/oncog/cogroom/domain/content/entity/ContentLecture.java, src/main/java/oncog/cogroom/domain/content/entity/ContentMember.java, src/main/java/oncog/cogroom/domain/content/entity/ContentReview.java, src/main/java/oncog/cogroom/domain/content/entity/ContentThumbnail.java, src/main/java/oncog/cogroom/domain/content/entity/RecommendedContent.java, src/main/java/oncog/cogroom/domain/content/enums/ContentLevel.java, src/main/java/oncog/cogroom/domain/content/enums/ContentStatus.java, src/main/java/oncog/cogroom/domain/content/enums/ContentType.java, src/main/java/oncog/cogroom/domain/daily/entity/Answer.java, src/main/java/oncog/cogroom/domain/daily/entity/Question.java, src/main/java/oncog/cogroom/domain/daily/entity/QuestionCategory.java, src/main/java/oncog/cogroom/domain/daily/entity/QuestionCategoryId.java, src/main/java/oncog/cogroom/domain/member/entity/Member.java, src/main/java/oncog/cogroom/domain/member/enums/MemberRole.java, src/main/java/oncog/cogroom/domain/member/enums/MemberStatus.java, src/main/java/oncog/cogroom/domain/member/enums/Provider.java, src/main/java/oncog/cogroom/domain/notice/entity/Notice.java, src/main/java/oncog/cogroom/domain/streak/entity/Streak.java, src/main/java/oncog/cogroom/domain/streak/entity/StreakLog.java
=> [FEAT] 패키지 구조 설정 및 엔티티 설정

build.gradle, src/main/java/oncog/cogroom/domain/content/entity/Content.java, src/main/java/oncog/cogroom/domain/content/entity/ContentExpectedEffect.java, src/main/java/oncog/cogroom/domain/content/entity/ContentLecture.java, src/main/java/oncog/cogroom/domain/content/entity/ContentMember.java, src/main/java/oncog/cogroom/domain/content/entity/ContentReview.java, src/main/java/oncog/cogroom/domain/daily/entity/Answer.java, src/main/java/oncog/cogroom/domain/daily/entity/Question.java, src/main/java/oncog/cogroom/domain/member/entity/Member.java, src/main/java/oncog/cogroom/domain/member/repository/MemberRepository.java, src/main/java/oncog/cogroom/domain/notice/entity/Notice.java, src/main/java/oncog/cogroom/domain/streak/entity/StreakLog.java, src/main/java/oncog/cogroom/global/common/entity/BaseTimeEntity.java, src/main/java/oncog/cogroom/global/common/entity/Category.java, src/main/java/oncog/cogroom/global/common/response/apiErrorResponse.java, src/main/java/oncog/cogroom/global/common/response/apiResponse.java, src/main/java/oncog/cogroom/global/config/JpaAuditingConfig.java, src/main/java/oncog/cogroom/global/config/SecurityConfig.java, src/main/java/oncog/cogroom/global/security/domain/CustomUserDetails.java, src/main/java/oncog/cogroom/global/security/jwt/JwtAuthenticationFilter.java, src/main/java/oncog/cogroom/global/security/jwt/JwtProvider.java, src/main/java/oncog/cogroom/global/security/service/CustomUserDetailService.java, src/main/resources/application.yml
- close #6 
- Spring Security 설정
- JWT Provider & filter 구현
- CustomUserDetails & CustomUserDetailsService 구현
- global 디렉토리 생성 및 구조 변경
- 추후 카카오 로그인 진행하면서 시큐리티 설정 변경 가능성 있습니다.
=> [Feat] Spring Security 설정 및 JWT 관련 클래스 구현

build.gradle, src/main/java/oncog/cogroom/CogroomApplication.java, src/main/java/oncog/cogroom/domain/auth/entity/EmailVerification.java, src/main/java/oncog/cogroom/domain/daily/entity/AssignedQuestion.java, src/main/java/oncog/cogroom/domain/daily/entity/Question.java, src/main/java/oncog/cogroom/domain/daily/enums/QuestionLevel.java, src/main/java/oncog/cogroom/domain/daily/respository/AssignedQuestionRepository.java, src/main/java/oncog/cogroom/domain/daily/respository/QuestionRepository.java, src/main/java/oncog/cogroom/domain/daily/scheduler/DailyQuestionAssignSchduler.java, src/main/java/oncog/cogroom/domain/daily/service/DailyQuestionAssignService.java, src/main/java/oncog/cogroom/domain/member/entity/Member.java, src/main/java/oncog/cogroom/domain/streak/entity/StreakLog.java, src/main/java/oncog/cogroom/global/common/entity/BaseTimeEntity.java
- close #10
- 날짜 생성되는 엔티티들의 날짜 포맷 설정
- 랜덤 데일리 질문 부여 기능 구현
- 배치 설정 추가
급한 스프린트(1차 - 데일리 등) 끝난 후에 배치 적용된 코드로 리팩토링할 예정입니다. 
당장은 데이터 수가 많지 않아 배치 설정만 해두고 코드에 적용은 하지 않았습니다.
=> [FEAT] 데일리 질문 랜덤 할당 기능 구현

build.gradle, src/main/java/oncog/cogroom/global/config/SwaggerConfig.java, src/main/resources/application.yml
=> [FEAT] Swagger 추가

src/main/java/oncog/cogroom/domain/content/entity/Content.java, src/main/java/oncog/cogroom/domain/daily/entity/Question.java, src/main/java/oncog/cogroom/domain/notice/entity/Notice.java, src/main/java/oncog/cogroom/global/common/entity/BaseEntity.java, src/main/java/oncog/cogroom/global/config/AuditorAwareConfig.java
- close #31
- createdBy, updatedBy 자동 추적 가능
=> [REFACTOR] createdBy, updatedBy BaseEntity 설정

src/main/java/oncog/cogroom/domain/daily/controller/DailyController.java, src/main/java/oncog/cogroom/domain/daily/dto/response/DailyQuestionResponseDTO.java, src/main/java/oncog/cogroom/domain/daily/exception/DailyErrorCode.java, src/main/java/oncog/cogroom/domain/daily/service/DailyService.java, src/main/java/oncog/cogroom/domain/member/service/MemberService.java, src/main/java/oncog/cogroom/domain/streak/controller/StreakController.java, src/main/java/oncog/cogroom/domain/streak/docs/StreakControllerDocs.java, src/main/java/oncog/cogroom/domain/streak/dto/response/StreakCalenderResponseDTO.java, src/main/java/oncog/cogroom/domain/streak/service/StreakService.java, src/main/java/oncog/cogroom/global/common/service/BaseService.java, src/main/java/oncog/cogroom/global/exception/domain/DailyException.java, src/main/java/oncog/cogroom/global/security/jwt/JwtProvider.java
- close #34 
- 데일리 질문 조회 에러코드 추가
- 에러코드 반환 및 null 결과 방지를 위해 jwtProvider.extractMemberId 반환 값을 optional로 수정
- 중복되는 에러코드를 공통 서비스에서 관리하기 위한 BaseService 추가
- 코드 리팩토링
- streak 기록 조회 시 시작 날짜를 월요일으로 변경
=> [REFACTOR] 데일리 질문 조회 에러 처리 및 코드 리팩토링

src/main/java/oncog/cogroom/domain/auth/controller/AuthController.java, src/main/java/oncog/cogroom/global/config/SwaggerConfig.java, src/main/java/oncog/cogroom/global/exception/swagger/ApiErrorCodeExample.java, src/main/java/oncog/cogroom/global/exception/swagger/ApiErrorCodeExamples.java, src/main/java/oncog/cogroom/global/exception/swagger/ExampleHolder.java
- close #36 
- ApiErrorCodeExamples, ApiErrorCodeExample 어노테이션 생성
- AuthController에 에러 처리 적용 예시 작성
- SwaggerConfig 수정
- 스웨거 에러 처리 커스텀 메소드 구현
=> [REFACTOR] 스웨거 커스텀 에러 문서화

src/main/java/oncog/cogroom/global/config/SecurityConfig.java, src/main/java/oncog/cogroom/global/s3/controller/LoadBalancerController.java
- close #47 
- 로드 밸런싱 헬스 체크를 위한 컨트롤러 구현
- 시큐리티 설정 파일 수정
=> [FEAT] healthCheck API 구현

src/main/java/oncog/cogroom/domain/daily/respository/AssignedQuestionRepository.java, src/main/java/oncog/cogroom/domain/daily/service/DailyService.java, src/main/java/oncog/cogroom/domain/streak/controller/StreakController.java
=> [FIX] streak, daily 메서드 수정

src/main/java/oncog/cogroom/domain/auth/controller/AuthController.java, src/main/java/oncog/cogroom/domain/daily/controller/docs/DailyControllerDocs.java, src/main/java/oncog/cogroom/domain/daily/dto/request/DailyAnswerRequestDTO.java, src/main/java/oncog/cogroom/domain/daily/dto/response/DailyQuestionResponseDTO.java, src/main/java/oncog/cogroom/domain/daily/exception/DailyErrorCode.java, src/main/java/oncog/cogroom/domain/daily/respository/AssignedQuestionRepository.java, src/main/java/oncog/cogroom/domain/daily/service/DailyQuestionAssignService.java, src/main/java/oncog/cogroom/domain/daily/service/DailyService.java, src/main/java/oncog/cogroom/domain/streak/controller/StreakController.java, src/main/java/oncog/cogroom/domain/streak/docs/StreakControllerDocs.java, src/main/java/oncog/cogroom/domain/streak/dto/response/StreakCalendarResponseDTO.java, src/main/java/oncog/cogroom/domain/streak/service/StreakService.java, src/main/java/oncog/cogroom/global/exception/GlobalExceptionHandler.java
- close #50
- 회원가입 시 데일리 질문 할당
- 데일리 질문 조회 시 assignedQuestionId 추가 응답
- 데일리 답변 등록, 수정 시 assignedQuestionId 추가 요청
- 데일리 답변 등록, 수정 시 에러코드 추가
- GlobalExceptionHandler의 mapFieldErrorToErrorCode 메서드 리팩토링
- 답변 수정, 등록에 추가된 에러코드는 동일합니다.
- mapFieldErrorToErrorCode 는 가독성 향상을 위해 if문 -> switch 문으로 변경하였습니다.
=> [REFACTOR] daily 메서드 오타 수정 및 누락 메서드 설정, 로직 추가

src/main/java/oncog/cogroom/CogroomApplication.java, src/main/java/oncog/cogroom/domain/daily/respository/AssignedQuestionRepository.java, src/main/java/oncog/cogroom/domain/daily/service/DailyService.java, src/main/resources/application.yml
- close #52
- 스프링 타임존 변경
- 데일리 질문 조회 안정성을 위한 메서드 변경
=> [FIX] 스프링 타임존 설정 및 쿼리 변경

src/main/java/oncog/cogroom/global/security/jwt/JwtProvider.java
- close #58 
- jwt 토큰 생성 로직 수정
- jwt 토큰 만료 시간 지정 기준 변경 ms -> s
=> [FIX] jwt 토큰 만료 시간 오류 수정

Dockerfile, docker-compose.yaml
=> [CI/CD] 도커파일 복구

Dockerfile
=> [CICD] docker file 문법 수정

src/main/java/oncog/cogroom/domain/daily/dto/response/DailyQuestionResponseDTO.java, src/main/java/oncog/cogroom/domain/daily/service/DailyService.java, src/main/java/oncog/cogroom/domain/streak/dto/response/StreakCalendarResponseDTO.java, src/main/java/oncog/cogroom/domain/streak/service/StreakService.java
- close #76
- 데일리 질문 조회 API 에서 streakDays 삭제
- 내 스트릭(물방울) 기록 조회 API에 streakDays 추가
=> [REFACTOR] 스트릭 기록 조회 API, 데일리 질문 조회 API 수정

src/main/java/oncog/cogroom/domain/content/entity/Content.java, src/main/java/oncog/cogroom/domain/daily/controller/DailyController.java, src/main/java/oncog/cogroom/domain/daily/service/DailyQuestionAssignService.java, src/main/java/oncog/cogroom/domain/daily/service/DailyService.java, src/main/java/oncog/cogroom/domain/streak/scheduler/StreakSchduler.java, src/main/java/oncog/cogroom/domain/streak/service/StreakService.java, src/main/java/oncog/cogroom/domain/streak/service/StreakUpdateService.java
- close #82
- streak update 로직 분리
- content 엔티티 기본값 설정
=> [REFACTOR] streakUpdateServce, streakService 로직 분리 및 주석 추가, content 엔티티 수정

src/main/java/oncog/cogroom/domain/auth/service/session/AuthSessionService.java
- close #108 
- 토큰 재발급 메소드 실행 시 Redis에 RefreshToken이 존재하는지 확인 여부 추가
=> [FIX] 로그아웃 후 토큰 재발급 가능 오류 수정

src/main/java/oncog/cogroom/domain/auth/service/social/AbstractAuthService.java
- close #111 
- 회원 닉네임 랜덤 생성 API 구현
- 회원가입 로직 수정
=> [FEAT] 랜덤 닉네임 생성 API 구현

src/main/java/oncog/cogroom/domain/auth/controller/AuthController.java, src/main/java/oncog/cogroom/domain/auth/controller/docs/AuthControllerDocs.java, src/main/java/oncog/cogroom/domain/auth/dto/request/AuthRequestDTO.java, src/main/java/oncog/cogroom/domain/auth/dto/response/AuthResponseDTO.java, src/main/java/oncog/cogroom/domain/auth/service/AuthService.java, src/main/java/oncog/cogroom/domain/auth/service/AuthServiceRouter.java, src/main/java/oncog/cogroom/domain/auth/service/EmailService.java, src/main/java/oncog/cogroom/domain/auth/service/social/AbstractAuthService.java
- close #114 
- 웰컴 메일 발송 API 구현
- Auth 관련 DTO 네이밍 수정
=> [FEAT] 웰컴 메일 발송 API 구현

src/main/java/oncog/cogroom/domain/streak/controller/StreakController.java, src/main/java/oncog/cogroom/domain/streak/controller/docs/StreakControllerDocs.java, src/main/java/oncog/cogroom/domain/streak/dto/response/StreakResponse.java, src/main/java/oncog/cogroom/domain/streak/service/StreakService.java
- close #118 
- 캘린더 api에서 dailyStreak 필드 삭제
=> [REFACTOR] 캘린더 api 응답 필드 수정

src/main/java/oncog/cogroom/domain/admin/controller/AdminController.java, src/main/java/oncog/cogroom/domain/admin/dto/request/AdminRequest.java, src/main/java/oncog/cogroom/domain/admin/dto/response/AdminResponse.java, src/main/java/oncog/cogroom/domain/admin/dto/response/PageResponse.java, src/main/java/oncog/cogroom/domain/admin/service/AdminService.java, src/main/java/oncog/cogroom/domain/auth/service/social/AbstractAuthService.java, src/main/java/oncog/cogroom/domain/member/repository/MemberRepository.java, src/main/java/oncog/cogroom/global/common/response/code/ApiErrorCode.java, src/main/java/oncog/cogroom/global/config/SecurityConfig.java, src/main/java/oncog/cogroom/global/security/jwt/JwtAccessDeniedHandler.java
- close #117 
- Spring Security Admin 필터 적용
- AccessDenied 에러 처리
- 어드민 회원 조회 api 구현
=> [FEAT] 어드민 회원 조회 API 구현

src/main/java/oncog/cogroom/domain/member/dto/response/MemberResponse.java, src/main/java/oncog/cogroom/domain/member/service/MemberService.java
- close #127 
- 사용자 정보 조회(summary) api 사용자 권한 필드 추가
=> [REFACTOR] 사용자 정보 조회 권한 필드 추가 (summary)

src/main/java/oncog/cogroom/domain/admin/dto/response/AdminResponse.java, src/main/java/oncog/cogroom/global/config/SecurityConfig.java
- close #129 
- Admin 권한 전체 페이지 접근 허용
- 어드민 회원 목록 조회 응답 값 추가 (memberId)
=> [REFACTOR] 어드민 회원 목록 조회 응답 값 추가

src/main/java/oncog/cogroom/domain/admin/dto/response/AdminResponse.java, src/main/java/oncog/cogroom/domain/admin/exception/AdminErrorCode.java, src/main/java/oncog/cogroom/domain/admin/service/AdminService.java, src/main/java/oncog/cogroom/global/common/response/code/ApiErrorCode.java
- close #131 
- 사용자 목록 조회 페이징 에러 처리
=> [REFACTOR] 어드민 사용자 목록 조회 페이징 에러 처리

src/main/java/oncog/cogroom/domain/admin/service/AdminService.java
- close #133
- mapsId 관련 매핑 추가
=> [FIX] 어드민 데일리 질문 추가 시 에러 수정

src/main/java/oncog/cogroom/domain/admin/service/AdminDailyService.java, src/main/java/oncog/cogroom/domain/admin/validator/AdminValidator.java
- close #139
- 카테고리 유효성 검사 코드 수정
=> [REFACTOR] 어드민 데일리 질문 조회 카테고리 리팩토링

src/main/java/oncog/cogroom/domain/daily/controller/docs/DailyControllerDocs.java, src/main/java/oncog/cogroom/domain/daily/dto/request/DailyRequest.java, src/main/java/oncog/cogroom/domain/daily/exception/DailyErrorCode.java
=> [REFACTOR] 데일리 질문 등록/수정 에러코드 수정

src/main/java/oncog/cogroom/domain/auth/entity/EmailVerification.java, src/main/java/oncog/cogroom/domain/auth/repository/EmailRepository.java, src/main/java/oncog/cogroom/domain/auth/service/EmailService.java, src/main/java/oncog/cogroom/domain/member/scheduler/MemberScheduler.java
- close #146 
- 이메일 인증 상태 변경 안되는 에러 수정
- 시간 만료된 인증 링크 정리하는 스케줄러 작성
=> [REFACTOR] 사용자 정보 수정 에러 수정

build.gradle, src/main/java/oncog/cogroom/domain/auth/controller/AuthController.java, src/main/java/oncog/cogroom/domain/auth/controller/docs/AuthControllerDocs.java, src/main/java/oncog/cogroom/domain/auth/service/EmailService.java, src/main/resources/templates/email-page.html, src/main/resources/templates/welcome-page.html
- close #148 
- 웰컴 이메일 페이지 적용
- 이메일 인증 페이지 적용
- 타임리프 적용
=> [REFACTOR] 이메일 인증 및 웰컴 이메일 페이지 적용

src/main/java/oncog/cogroom/global/config/SecurityConfig.java
- close #153
- 프론트 스테이지 url cors 설정
=> [REFACTOR] 프론트 스테이지 url cors 설정

src/main/java/oncog/cogroom/domain/member/service/MemberService.java
- close #157 
- 프로필 사진 URL을 Null로 보내면 TEMP에서 PROFILE로 이동시키는 로직 실행 안하도록 수정
=> [FIX] 사용자 정보 수정 profileUrl null 에러처리

src/main/java/oncog/cogroom/domain/auth/controller/AuthController.java, src/main/java/oncog/cogroom/domain/auth/controller/docs/AuthControllerDocs.java, src/main/java/oncog/cogroom/domain/auth/service/EmailService.java, src/main/java/oncog/cogroom/global/config/SecurityConfig.java, src/main/java/oncog/cogroom/global/config/SwaggerConfig.java
- close #162 
- cors 도메인 추가
- 이메일 인증 상태 반환 api 수정
=> [REFACTOR] 이메일 인증 상태 반환 API 수정

build.gradle, src/main/java/oncog/cogroom/domain/member/scheduler/MemberScheduler.java, src/main/resources/application.yml
- close #171 
- prometheus.yml 작성
- rules.yml 작성
- 의존성 추가
=> [FEAT] prometheus 모니터링 설정
